// The cross-language conformance test for the `call_sig` v3 signed payload (#197).
//
// `conformance/call_sig_v3_payload_vector.json` is a byte-identical copy of the runtime's fixture,
// generated by an implementation independent of both Rust ones. A self-consistent signature is not a
// conformant one, so these tests compare against those bytes, not our own output. There is NO bless
// mode: a mismatch is a contract break.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { ed25519 } from "@noble/curves/ed25519";

import { CALL_SIG_V3_CONTEXT, callSigV3, callSigV3Payload, type CallSigV3Fields } from "../src/crypto.js";

type Case = {
  name: string;
  ticket_hex: string;
  tool_input_digest: string;
  tool_name: string;
  agent_id: string;
  subject: string;
  subjects: string[];
  client_request_id: string;
  session_id: string;
  features: [string, string][];
  payload_hex: string;
};

const VECTOR = JSON.parse(
  readFileSync(
    join(dirname(fileURLToPath(import.meta.url)), "..", "..", "conformance", "call_sig_v3_payload_vector.json"),
    "utf8",
  ),
) as { domain: string; cases: Case[] };

const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
const fields = (c: Case): CallSigV3Fields => ({
  ticket: Uint8Array.from(Buffer.from(c.ticket_hex, "hex")),
  toolInputDigest: c.tool_input_digest,
  toolName: c.tool_name,
  agentId: c.agent_id,
  subject: c.subject,
  subjects: c.subjects,
  clientRequestId: c.client_request_id,
  sessionId: c.session_id,
  features: Object.fromEntries(c.features),
});

test("the v3 vector is present and populated", () => {
  // An emptied vector would iterate zero cases below and report green.
  assert.ok(VECTOR.cases.length >= 7, "the vector lost cases; it pins a wire contract");
});

test("the v3 context tag matches the vector", () => {
  assert.equal(CALL_SIG_V3_CONTEXT, VECTOR.domain);
});

for (const c of VECTOR.cases) {
  test(`v3 payload matches the vector bytes: ${c.name}`, () => {
    assert.equal(hex(callSigV3Payload(fields(c))), c.payload_hex);
  });
}

test("callSigV3 is Ed25519 over the v3 payload", () => {
  const seed = new Uint8Array(32).map((_, i) => i);
  const f = fields(VECTOR.cases.find((c) => c.name === "full")!);
  assert.ok(ed25519.verify(callSigV3(seed, f), callSigV3Payload(f), ed25519.getPublicKey(seed)));
});

test("features sort by UTF-8 bytes, not by JavaScript's UTF-16 string order", () => {
  // U+FFFF is EF BF BF in UTF-8 and U+10000 is F0 90 80 80, so bytewise U+FFFF sorts first. In
  // UTF-16, U+10000 is the surrogate pair D800 DC00, which sorts BEFORE FFFF. The vector has no case
  // that tells the two orders apart, so this pins it.
  const base = fields(VECTOR.cases[0]!);
  const p = callSigV3Payload({ ...base, features: { "\u{10000}": "b", "￿": "a" } });
  const want =
    "04000000" + "02000000" + "03000000efbfbf" + "0100000061" + "04000000f0908080" + "0100000062";
  assert.equal(hex(p).slice(-want.length), want);
});
