// The enrolment proof-of-possession (#205, seam-runtime #1157 / #1164).
//
// `conformance/enroll_pop_v1_payload_vector.json` is a byte-identical copy of the runtime's fixture,
// generated by an implementation independent of the Rust one. A self-consistent signature is not a
// conformant one, so the payload AND the signature are compared to those bytes. There is NO bless mode:
// a mismatch is a contract break.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { create, fromBinary, toBinary } from "@bufbuild/protobuf";
import type { DescMessage, DescMethodUnary, MessageInitShape } from "@bufbuild/protobuf";
import type { Transport, UnaryResponse } from "@connectrpc/connect";

import { Agent } from "../src/client.js";
import { SeamAdminClient } from "../src/admin.js";
import { InvalidArgumentError } from "../src/errors.js";
import {
  ENROLL_POP_V1_CONTEXT,
  enrollPop,
  enrollPopPayload,
  enrollProofToRest,
  validateEnrollPopNonce,
  verifyEnrollPop,
  type EnrollProof,
} from "../src/crypto.js";
import { EnrollTenantRequestSchema, type EnrollTenantRequest } from "../gen/seam/api/v1/seam_pb.js";

type Case = {
  name: string;
  why: string;
  seed_hex: string;
  subject_aid: string;
  tenant: string;
  namespace: string;
  issued_at_ms: number;
  nonce: string;
  payload_hex: string;
  signature: string;
};

const VECTOR = JSON.parse(
  readFileSync(
    join(dirname(fileURLToPath(import.meta.url)), "..", "..", "conformance", "enroll_pop_v1_payload_vector.json"),
    "utf8",
  ),
) as { domain: string; cases: Case[] };

const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
const fromHex = (s: string) => Uint8Array.from(Buffer.from(s, "hex"));
const fromB64url = (s: string) => Uint8Array.from(Buffer.from(s, "base64url"));

test("the enroll-pop vector is present and populated", () => {
  // An emptied vector would iterate zero cases below and report green.
  assert.ok(VECTOR.cases.length >= 6, "the vector lost cases; it pins a wire contract");
});

test("the enroll-pop context tag matches the vector", () => {
  assert.equal(ENROLL_POP_V1_CONTEXT, VECTOR.domain);
});

for (const c of VECTOR.cases) {
  test(`enroll-pop payload matches the vector bytes: ${c.name}`, () => {
    const got = enrollPopPayload({
      subjectAid: c.subject_aid,
      tenant: c.tenant,
      namespace: c.namespace,
      issuedAtMs: c.issued_at_ms,
      nonce: c.nonce,
    });
    assert.equal(hex(got), c.payload_hex, c.why);
    // A bigint issuedAtMs frames identically to the number.
    assert.equal(
      hex(enrollPopPayload({ subjectAid: c.subject_aid, tenant: c.tenant, namespace: c.namespace, issuedAtMs: BigInt(c.issued_at_ms), nonce: c.nonce })),
      c.payload_hex,
    );
  });

  test(`enroll-pop signature matches the vector, raw and base64url: ${c.name}`, () => {
    const agent = new Agent(fromHex(c.seed_hex));
    assert.equal(agent.aid, c.subject_aid);
    const proof = agent.enrolmentProof(c.tenant, c.namespace, { issuedAtMs: c.issued_at_ms, nonce: c.nonce });
    // RAW 64 bytes — the gRPC form.
    assert.equal(proof.signature.length, 64);
    assert.deepEqual(proof.signature, fromB64url(c.signature));
    // Unpadded base64url — the REST form.
    assert.deepEqual(enrollProofToRest(proof), {
      issued_at_ms: c.issued_at_ms,
      nonce: c.nonce,
      signature: c.signature,
    });
    assert.equal(proof.issuedAtMs, BigInt(c.issued_at_ms));
    assert.deepEqual(
      enrollPop(agent.seed, { tenant: c.tenant, namespace: c.namespace, issuedAtMs: c.issued_at_ms, nonce: c.nonce }),
      proof,
    );
    assert.ok(
      verifyEnrollPop(
        { subjectAid: c.subject_aid, tenant: c.tenant, namespace: c.namespace, issuedAtMs: c.issued_at_ms, nonce: c.nonce },
        proof.signature,
      ),
    );
  });
}

test("a proof for tenant A / namespace X does not verify for B / Y", () => {
  const agent = new Agent(new Uint8Array(32).map((_, i) => i));
  const proof = agent.enrolmentProof("tenant-a", "ns-x", { issuedAtMs: 1_760_000_000_000n, nonce: "n0" });
  const verifies = (o: Partial<{ subjectAid: string; tenant: string; namespace: string; issuedAtMs: bigint; nonce: string }>) =>
    verifyEnrollPop(
      { subjectAid: agent.aid, tenant: "tenant-a", namespace: "ns-x", issuedAtMs: proof.issuedAtMs, nonce: proof.nonce, ...o },
      proof.signature,
    );
  assert.ok(verifies({}));
  assert.ok(!verifies({ tenant: "tenant-b" }));
  assert.ok(!verifies({ namespace: "ns-y" }));
  assert.ok(!verifies({ tenant: "tenant-b", namespace: "ns-y" }));
  assert.ok(!verifies({ subjectAid: new Agent(new Uint8Array(32).fill(9)).aid }));
  assert.ok(!verifies({ issuedAtMs: proof.issuedAtMs + 1n }));
  assert.ok(!verifies({ nonce: "n1" }));
});

test("enrolmentProof defaults to now and a fresh 22-char nonce", () => {
  const agent = new Agent(new Uint8Array(32).map((_, i) => i));
  const before = BigInt(Date.now());
  const a = agent.enrolmentProof("acme", "fraud");
  const b = agent.enrolmentProof("acme", "fraud");
  const after = BigInt(Date.now());
  assert.ok(before <= a.issuedAtMs && a.issuedAtMs <= after);
  assert.equal(a.nonce.length, 22);
  assert.equal(validateEnrollPopNonce(a.nonce), a.nonce);
  assert.notEqual(a.nonce, b.nonce, "the default nonce must be random per proof");
  assert.ok(
    verifyEnrollPop({ subjectAid: agent.aid, tenant: "acme", namespace: "fraud", issuedAtMs: a.issuedAtMs, nonce: a.nonce }, a.signature),
  );
});

test("nonce validation: 1..=128 chars of [A-Za-z0-9_-]", () => {
  for (const ok of ["a", "A-z_09", "x".repeat(128)]) assert.equal(validateEnrollPopNonce(ok), ok);
  const agent = new Agent(new Uint8Array(32));
  for (const bad of ["", "x".repeat(129), "has space", "pad=", "a+b", "a/b", "é", "a.b", "ok\n"]) {
    assert.throws(() => validateEnrollPopNonce(bad), RangeError, JSON.stringify(bad));
    assert.throws(() => agent.enrolmentProof("acme", "fraud", { nonce: bad }), RangeError, JSON.stringify(bad));
  }
});

test("issuedAtMs is a u64", () => {
  const agent = new Agent(new Uint8Array(32));
  assert.throws(() => agent.enrolmentProof("acme", "fraud", { issuedAtMs: -1, nonce: "n" }), RangeError);
  assert.throws(() => agent.enrolmentProof("acme", "fraud", { issuedAtMs: 1n << 64n, nonce: "n" }), RangeError);
});

// ── enrollTenant wiring ──────────────────────────────────────────────────────────────────────────

function recordingAdmin(): { admin: SeamAdminClient; seen: EnrollTenantRequest[] } {
  const seen: EnrollTenantRequest[] = [];
  const transport = {
    async unary<I extends DescMessage, O extends DescMessage>(
      method: DescMethodUnary<I, O>,
      _signal: AbortSignal | undefined,
      _timeoutMs: number | undefined,
      _headers: HeadersInit | undefined,
      input: MessageInitShape<I>,
    ): Promise<UnaryResponse<I, O>> {
      // Round-trip through the wire encoding, so "carried" means "on the wire", not "in an object".
      const req = fromBinary(
        EnrollTenantRequestSchema,
        toBinary(EnrollTenantRequestSchema, create(EnrollTenantRequestSchema, input as MessageInitShape<typeof EnrollTenantRequestSchema>)),
      );
      seen.push(req);
      return {
        stream: false,
        service: method.parent,
        method,
        header: new Headers(),
        trailer: new Headers(),
        message: create(method.output, { aid: req.subjectAid, tenant: req.tenant, namespace: req.namespace } as unknown as MessageInitShape<O>),
      };
    },
    async stream() {
      throw new Error("no streams here");
    },
  } as unknown as Transport;
  return { admin: new SeamAdminClient(transport), seen };
}

test("enrollTenant carries pop when given and omits it when not", async () => {
  const agent = new Agent(new Uint8Array(32).map((_, i) => i));
  const proof = agent.enrolmentProof("acme", "fraud");
  const { admin, seen } = recordingAdmin();

  await admin.enrollTenant(agent.aid, "acme", "fraud", proof);
  await admin.enrollTenant(agent.aid, "acme", "fraud");
  const [withPop, withoutPop] = seen;

  assert.ok(withPop!.pop, "pop was not on the wire");
  assert.equal(withPop!.pop.issuedAtMs, proof.issuedAtMs);
  assert.equal(withPop!.pop.nonce, proof.nonce);
  assert.deepEqual(withPop!.pop.signature, proof.signature); // RAW 64 bytes on gRPC
  assert.ok(
    verifyEnrollPop(
      {
        subjectAid: withPop!.subjectAid,
        tenant: withPop!.tenant,
        namespace: withPop!.namespace,
        issuedAtMs: withPop!.pop.issuedAtMs,
        nonce: withPop!.pop.nonce,
      },
      withPop!.pop.signature,
    ),
  );
  assert.equal(withoutPop!.pop, undefined, "pop must be absent when not given");
});

test("enrollTenant refuses a malformed pop with InvalidArgumentError before any RPC", async () => {
  const sig = new Uint8Array(64);
  const bad: [string, EnrollProof][] = [
    ["empty nonce", { issuedAtMs: 1n, nonce: "", signature: sig }],
    ["bad char", { issuedAtMs: 1n, nonce: "a b", signature: sig }],
    ["long nonce", { issuedAtMs: 1n, nonce: "x".repeat(129), signature: sig }],
    ["short sig", { issuedAtMs: 1n, nonce: "ok", signature: new Uint8Array(63) }],
    ["b64 sig", { issuedAtMs: 1n, nonce: "ok", signature: "A".repeat(86) as unknown as Uint8Array }],
    ["negative time", { issuedAtMs: -1n, nonce: "ok", signature: sig }],
    ["number time", { issuedAtMs: 1 as unknown as bigint, nonce: "ok", signature: sig }],
  ];
  for (const [name, pop] of bad) {
    const { admin, seen } = recordingAdmin();
    await assert.rejects(admin.enrollTenant("aid:x", "acme", "fraud", pop), InvalidArgumentError, name);
    assert.equal(seen.length, 0, `${name}: a malformed pop reached the wire`);
  }
});
