#!/usr/bin/env bash
#
# Copy the partner-facing packages of one released version from Cloudsmith
# `zer07labs/internal` into `zer07labs/partner`.
#
# WHY A SECOND REPO AT ALL. `internal` holds the thirteen private runtime crates
# (seam-kernel, seam-crypto, seam-store, seam-kms-vault, seamd) and
# seam-learning-keys. Cargo crates ship SOURCE, so a token that can read
# `internal` is a token that can read the closed half of the product. No partner
# can ever hold one. `partner` exists so there is something a partner CAN be
# given a token to, containing only what they install.
#
# ── THE VERB IS `copy`, AND THAT IS NOT A STYLE CHOICE ────────────────────────
# cloudsmith-cli spells the two operations:
#
#     copy|cp             Copy a package to another repository.
#     move|mv|promote     Move (promote) a package to another repo.
#
# `promote` is an alias for MOVE. Reaching for the word in the ticket would take
# the artifact OUT of `internal` — deleting the version every internal consumer
# resolves, with no undo. Verified against cloudsmith-cli 1.11.1 (`cloudsmith
# move --help`), which is the version the workflow pins. Do not "simplify" this
# to `cloudsmith promote`.
#
# ── `copy` IS NOT IDEMPOTENT, AND IT DOES NOT TELL YOU ────────────────────────
# Copying a package that is ALREADY in the destination exits 0 and creates a
# SECOND COPY under a new slug. Measured, not assumed — two runs of
#
#     cloudsmith copy zer07labs/internal/seam-sdk-0143tgz-vsd0 partner
#
# left `partner` holding @zer07labs/seam-sdk@0.14.3 twice, as slugs
# `…-7g1f` and `…-7dvf`. So idempotency CANNOT be implemented the way the
# publish jobs do it (tolerate an "already uploaded" error) — there is no error
# to tolerate. It has to be a destination check BEFORE the copy, which is what
# `_already_there` below is. Re-running this script is safe; deleting that check
# silently accumulates duplicate versions in a partner-facing repo.
#
# ── SLUGS ARE PER FILE, NOT PER VERSION ───────────────────────────────────────
# `copy` addresses a package by SLUG (`owner/repo/slug`), which is generated by
# Cloudsmith (`seam-sdk-0143tgz-vsd0`) and cannot be constructed from the name
# and version — it must be looked up. And one python version is TWO packages:
# an sdist and a wheel (`seam_sdk-0.14.3.tar.gz`, `seam_sdk-0.14.3-py3-none-any.whl`),
# each with its own slug. Resolving "the slug" for a version and copying it
# would promote the wheel and leave the sdist behind, so this loops over every
# row the query returns.
#
# ── THE KEY'S SCOPE DEPENDS ON A REPO SETTING, NOT JUST ITS GRANT ─────────────
# `ci-partner-promote` holds an explicit `Read` on `internal`. That alone did NOT
# stop it writing there: a Cloudsmith repo's `default_privilege` applies to every
# member and service account on top of explicit grants, and `internal` was set to
# `Admin`. A raw package push with this key succeeded. It is now `None`, and the
# same push returns 403. If `internal.default_privilege` is ever set back to
# `Admin`, this key silently regains write on `internal` and no test here can see
# it — the setting lives in Cloudsmith, not in this repo.
#
# Usage:  scripts/promote-to-partner.sh 0.14.3          one version
#         scripts/promote-to-partner.sh --since 0.7.47   that version and every later one
#         CLOUDSMITH_PARTNER_API_KEY must be set (raw key, no "Bearer " prefix).
#
# `--since` is the BACKFILL path: it enumerates the versions `internal` actually
# holds for the allowlisted packages and promotes each one, so the partner repo
# can be brought up to date without waiting for the next release to fire the
# workflow. It reads the same allowlist as everything else — there is exactly one
# list in this file and no second place to forget to update.
#
# Exit codes:  0 promoted or already present · 1 refusal (see the message)
set -euo pipefail

OWNER="zer07labs"
SOURCE_REPO="internal"
DEST_REPO="partner"

# ── THE ALLOWLIST ─────────────────────────────────────────────────────────────
# Literal `name|format` pairs. There are no globs, no prefix matches and no
# "everything except" here, deliberately: a partner-facing repo is the one place
# where a pattern that grows a new match on its own is indefensible. Adding a
# package is an edit to THIS list, reviewed like any other change.
#
# FORMAT IS PART OF THE KEY, not decoration. `internal` already carries a cargo
# crate called `seam-verify`, and the day something publishes a CRATE named
# `seam-sdk`, a name-only match would promote Rust source into the partner repo.
# Pinning the format means such a package does not match this list at all.
#
# The npm and python packages are named DIFFERENTLY for the same artifact
# (`@zer07labs/seam-sdk` vs `seam-sdk`) — that is npm scoping, not a typo.
PARTNER_ALLOWLIST=(
  "@zer07labs/seam-sdk|npm"
  "seam-sdk|python"
)

die() { echo "::error::$*" >&2; exit 1; }

SINCE=""
VERSION=""
case "${1:-}" in
  --since) SINCE="${2:-}"; [ -n "$SINCE" ] || die "--since needs a version (e.g. --since 0.7.47)." ;;
  "")      die "no version given. Usage: $0 <version>   |   $0 --since <version>" ;;
  -*)      die "unknown option '$1'. Usage: $0 <version>   |   $0 --since <version>" ;;
  *)       VERSION="$1" ;;
esac

# A tag, not a version, is the likely mistake — the workflow strips the leading
# `v` before calling. Catch it here rather than emitting a query that matches
# nothing and reporting it as a missing package.
for _v in "$VERSION" "$SINCE"; do
  case "$_v" in
    v*) die "got the TAG '$_v', not a version. Strip the leading 'v' — Cloudsmith versions are '${_v#v}'." ;;
  esac
done

[ -n "${CLOUDSMITH_PARTNER_API_KEY:-}" ] \
  || die "CLOUDSMITH_PARTNER_API_KEY is not set — cannot promote. This is the PARTNER key (write on ${DEST_REPO}, read on ${SOURCE_REPO}); do not substitute the publishing key."
case "${CLOUDSMITH_PARTNER_API_KEY}" in
  "Bearer "*|"Token "*)
    # The org's Cargo token is stored WITH a literal "Bearer " prefix because
    # cargo's token provider wants it. The CLI's --api-key wants the raw value,
    # and a prefixed key fails as a 401 that reads like a permissions problem.
    die "CLOUDSMITH_PARTNER_API_KEY carries a \"Bearer \"/\"Token \" prefix. The CLI wants the RAW key — that prefix is a Cargo convention and will surface as a confusing 401." ;;
esac

# FAIL CLOSED ON AN EMPTY LIST. An allowlist that has been emptied — by a bad
# edit, a botched merge — would otherwise make this script a silent no-op that
# still reports success, which is the one outcome a fail-closed design must not
# have.
[ "${#PARTNER_ALLOWLIST[@]}" -gt 0 ] \
  || die "the promotion allowlist is EMPTY. Refusing to report a successful promotion that copied nothing."

CS=(cloudsmith)

# Every lookup is an exact-anchored query: `^name$` and `^version$`. Cloudsmith's
# default search is a substring match, so an unanchored `seam-sdk` also matches
# `@zer07labs/seam-sdk` (and would match a hypothetical `seam-sdk-extras`).
# Anchoring is what makes the allowlist mean what it says.
_query() {  # _query <repo> <name> <format> <version> -> JSON rows on stdout
  "${CS[@]}" list packages "${OWNER}/$1" \
    -q "name:^$2\$ version:^$4\$ format:$3" \
    -k "${CLOUDSMITH_PARTNER_API_KEY}" -F json -l 100 2>/dev/null
}

# Every version of one allowlisted package, unfiltered. Only used by --since.
_all_versions() {  # _all_versions <name> <format> -> versions on stdout
  "${CS[@]}" list packages "${OWNER}/${SOURCE_REPO}" \
    -q "name:^$1\$ format:$2" \
    -k "${CLOUDSMITH_PARTNER_API_KEY}" -F json -l 500 2>/dev/null \
  | python3 -c '
import json,sys
d=json.load(sys.stdin); rows=d.get("data",d) if isinstance(d,dict) else d
for v in {r["version"] for r in rows}: print(v)'
}

# LOOP, do not `print("\n".join(...))`. On an empty result that join prints one
# EMPTY LINE, and the caller reads that as a row. It is not a cosmetic
# difference: it defeated the "allowlisted name matched nothing" refusal below,
# which saw one blank row, took the blank filename as already-present, and
# skipped the package silently — the precise outcome the allowlist exists to
# make impossible. Printing per row emits nothing for nothing.
_filenames() { python3 -c '
import json,sys
d=json.load(sys.stdin); rows=d.get("data",d) if isinstance(d,dict) else d
for r in rows: print(r["filename"])'; }

# No f-string here on purpose: an f-string expression cannot contain a
# backslash before Python 3.12, and `f"{r[\"slug\"]}"` is a SyntaxError on the
# 3.11 the publish jobs pin. The failure mode that caused is worth remembering —
# the helper died, the row list came back empty, and the script refused with
# "allowlisted package has NO version 0.14.3", which is a real and reassuring
# message for a completely fictitious reason.
_slugs_and_files() { python3 -c '
import json,sys
d=json.load(sys.stdin); rows=d.get("data",d) if isinstance(d,dict) else d
for r in rows: print(r["slug"] + "\t" + r["filename"])'; }

promoted=0; skipped=0

promote_version() {  # promote_version <version>
  local ver="$1" entry name format src dst_files row slug file
  echo "promoting ${OWNER}/${SOURCE_REPO} → ${OWNER}/${DEST_REPO} at version ${ver}"

  for entry in "${PARTNER_ALLOWLIST[@]}"; do
    name="${entry%%|*}"; format="${entry##*|}"
    [ -n "$name" ] && [ -n "$format" ] && [ "$name" != "$entry" ] \
      || die "malformed allowlist entry '$entry' — expected 'name|format'."

    src="$(_query "$SOURCE_REPO" "$name" "$format" "$ver")" \
      || die "could not query ${OWNER}/${SOURCE_REPO} for ${name} ${ver} (${format})."

    mapfile -t rows < <(printf '%s' "$src" | _slugs_and_files)
    # A NAME ON THE LIST THAT MATCHED NOTHING IS A REFUSAL, not a skip. If
    # `seam-sdk` is expected at this version and `internal` does not have it, the
    # release did not land the way the caller believes it did, and promoting the
    # rest of the list while staying green would hide that.
    [ "${#rows[@]}" -gt 0 ] \
      || die "allowlisted package '${name}' (${format}) has NO version ${ver} in ${OWNER}/${SOURCE_REPO}. Refusing to report a partial promotion as success."

    # The destination, read ONCE per package rather than once per file.
    dst_files="$(_query "$DEST_REPO" "$name" "$format" "$ver" | _filenames || true)"

    for row in "${rows[@]}"; do
      slug="${row%%$'\t'*}"; file="${row##*$'\t'}"
      # Match on FILENAME, not on version. One python version is an sdist AND a
      # wheel, so "is this version in partner?" is the wrong question — it is
      # true as soon as either half has landed, and the other half would never
      # be copied.
      if printf '%s\n' "$dst_files" | grep -qxF "$file"; then
        echo "  = ${name} ${ver} (${format}) ${file} — already in ${DEST_REPO}, not copying again"
        skipped=$((skipped + 1))
        continue
      fi
      echo "  + ${name} ${ver} (${format}) ${file}  [${slug}]"
      "${CS[@]}" copy "${OWNER}/${SOURCE_REPO}/${slug}" "${DEST_REPO}" \
        -k "${CLOUDSMITH_PARTNER_API_KEY}" \
        || die "copy of ${slug} (${name} ${ver}) into ${DEST_REPO} failed."
      promoted=$((promoted + 1))
    done
  done
}

if [ -n "$SINCE" ]; then
  # Enumerate from the FIRST allowlist entry and intersect with the rest below.
  # Versions come from what `internal` actually holds, never from a hand-kept
  # list — the repo has gaps (0.7.54, 0.7.55 and others were never published),
  # and a generated range would refuse on versions that do not exist.
  first="${PARTNER_ALLOWLIST[0]}"
  mapfile -t candidates < <(_all_versions "${first%%|*}" "${first##*|}" | sort -V)
  [ "${#candidates[@]}" -gt 0 ] \
    || die "found no versions of '${first%%|*}' in ${OWNER}/${SOURCE_REPO} — refusing to call that a complete backfill."

  # `sort -V` orders versions the way a human reads them; a lexical sort puts
  # 0.14.3 before 0.7.47, which would silently drop most of the backfill.
  selected=()
  for v in "${candidates[@]}"; do
    [ "$(printf '%s\n%s\n' "$SINCE" "$v" | sort -V | head -1)" = "$SINCE" ] && selected+=("$v")
  done
  [ "${#selected[@]}" -gt 0 ] \
    || die "no version >= ${SINCE} exists in ${OWNER}/${SOURCE_REPO}."

  echo "backfill: ${#selected[@]} version(s) >= ${SINCE} — ${selected[*]}"
  echo
  for v in "${selected[@]}"; do
    # A version present for npm but not python (or the reverse) is a genuine
    # inconsistency worth stopping on, which is what promote_version does.
    promote_version "$v"
  done
else
  promote_version "$VERSION"
fi

# Belt and braces on the fail-closed promise: reaching the end having neither
# copied nor recognised anything means the loop above did not do what its exit
# status claims.
[ $((promoted + skipped)) -gt 0 ] \
  || die "no package was promoted or recognised — refusing to exit 0."

echo
echo "done: ${promoted} copied, ${skipped} already present"
