"""The declared ``protobuf`` floor must match the gencode actually compiled into ``_gen``.

This exists because the mismatch already shipped. ``pyproject.toml`` declared ``protobuf>=5`` while
the generated stubs were emitted by protoc gencode **7.35.1**, and protobuf's runtime-version check
rejects a runtime older than the gencode that produced a file. So a resolver was free to install
runtime 6.x, everything installed cleanly, and then ``import seam_sdk`` raised
``google.protobuf.runtime_version.VersionError``.

The consequence landed in a consumer, not here: it took the seam-adapters core suite from 88 passing
to **zero collected**, and from inside that repo it looked like their problem. A packaging defect
whose only symptom appears in somebody else's CI is exactly the kind this file has to catch.

Pinning a number would not have been enough. ``_gen`` is regenerated by ``make generate`` against
buf's REMOTE plugins, which track latest — so the gencode version moves on its own schedule, without
anyone editing this repo's dependency list. The floor is therefore **derived from the emitted stubs
and asserted**, so a regenerate that outruns the declared floor fails here rather than in a
consumer's import.
"""

from __future__ import annotations

import pathlib
import re

import pytest

REPO = pathlib.Path(__file__).parents[2]
PYPROJECT = REPO / "python" / "pyproject.toml"
GENERATED = (
    REPO / "python" / "seam_sdk" / "_gen" / "seam" / "api" / "v1" / "seam_pb2.py"
)

#: protoc emits this call at the top of every generated module, carrying the gencode version as
#: positional args: ``ValidateProtobufRuntimeVersion(Domain.PUBLIC, major, minor, patch, suffix, file)``.
_GENCODE_RE = re.compile(
    r"ValidateProtobufRuntimeVersion\(\s*"
    r"_runtime_version\.Domain\.\w+\s*,\s*"
    r"(?P<major>\d+)\s*,\s*(?P<minor>\d+)\s*,\s*(?P<patch>\d+)\s*,",
    re.MULTILINE,
)

_FLOOR_RE = re.compile(
    r'"protobuf>=(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+),<(?P<cap>\d+)"'
)


def _gencode_version() -> tuple[int, int, int]:
    if not GENERATED.exists():
        pytest.skip(
            f"{GENERATED.relative_to(REPO)} is absent — run `make generate` first "
            "(the CI job does, before it runs these tests)"
        )
    match = _GENCODE_RE.search(GENERATED.read_text(encoding="utf-8"))
    assert match is not None, (
        f"no ValidateProtobufRuntimeVersion call found in {GENERATED.relative_to(REPO)} — "
        "protoc changed its preamble, and this guard must be updated to keep deriving the floor "
        "rather than silently passing"
    )
    return int(match["major"]), int(match["minor"]), int(match["patch"])


def _declared_floor() -> tuple[tuple[int, int, int], int]:
    match = _FLOOR_RE.search(PYPROJECT.read_text(encoding="utf-8"))
    assert match is not None, (
        "python/pyproject.toml must declare protobuf as `protobuf>=X.Y.Z,<N` — a bare `>=N` "
        "cannot express the same-major requirement protobuf's runtime check enforces"
    )
    floor = (int(match["major"]), int(match["minor"]), int(match["patch"]))
    return floor, int(match["cap"])


def test_the_declared_floor_is_at_least_the_gencode_in_the_generated_stubs():
    """The failing case, stated as protobuf states it: a runtime older than the gencode is invalid.

    If this goes red after a `make generate`, the fix is to raise the floor in pyproject.toml to
    the version printed below — not to relax this assertion.
    """
    gencode = _gencode_version()
    floor, _ = _declared_floor()
    assert floor >= gencode, (
        f"the generated stubs carry gencode {'.'.join(map(str, gencode))} but pyproject declares "
        f"protobuf>={'.'.join(map(str, floor))}. A resolver may install a runtime older than the "
        "gencode, which raises VersionError at `import seam_sdk` — in the CONSUMER's process, not "
        f"ours. Raise the floor to >={'.'.join(map(str, gencode))}."
    )


def test_the_floor_caps_the_major_version_the_gencode_requires():
    """Same-major is a hard requirement of protobuf's check, not a compatibility preference — a
    runtime one major ahead is rejected just as firmly as one behind."""
    gencode = _gencode_version()
    floor, cap = _declared_floor()
    assert floor[0] == gencode[0], (
        f"floor major {floor[0]} != gencode major {gencode[0]}; protobuf requires the SAME major"
    )
    assert cap == gencode[0] + 1, (
        f"the upper bound must be <{gencode[0] + 1} so the resolver cannot pick protobuf "
        f"{gencode[0] + 1}.x, which the gencode rejects; it is currently <{cap}"
    )


def test_the_installed_runtime_satisfies_the_floor_this_package_declares():
    """The end-to-end version of the two checks above: whatever is installed here must actually be
    able to import the generated stubs.

    Cheap, and it is the exact assertion whose absence let the skew reach a consumer — every other
    test in this suite imports `seam_sdk` transitively and would fail too, but with a stack trace
    that names protobuf rather than the packaging metadata that caused it.
    """
    from google.protobuf import runtime_version

    floor, cap = _declared_floor()
    installed = (runtime_version.MAJOR, runtime_version.MINOR, runtime_version.PATCH)
    assert floor <= installed, (
        f"installed protobuf {'.'.join(map(str, installed))} is below the declared floor "
        f"{'.'.join(map(str, floor))} — this environment does not satisfy the package's own metadata"
    )
    assert installed[0] < cap, (
        f"installed protobuf {'.'.join(map(str, installed))} is at or above the declared cap <{cap}"
    )


def test_importing_the_package_actually_works():
    """The smoke test whose absence is the whole story.

    A VersionError is raised at IMPORT, so it cannot be caught by any test that has already
    imported the package — every module here would simply fail to collect, which is precisely how
    this manifested downstream (a whole suite reporting zero tests). Importing in an explicit,
    named test means the failure says what it is.
    """
    import importlib

    module = importlib.import_module("seam_sdk")
    assert hasattr(module, "SeamClient")
    importlib.import_module("seam_sdk.aio")
    importlib.import_module("seam_sdk.admin")
