"""The enrolment proof-of-possession (#205, seam-runtime #1157 / #1164).

Asserts against `conformance/enroll_pop_v1_payload_vector.json`, a byte-identical copy of the runtime's
fixture, generated by an implementation independent of the Rust one. A self-consistent signature is not
a conformant one, so the payload AND the signature are compared to those bytes. There is no bless mode:
a mismatch is a contract break.
"""

from __future__ import annotations

import base64
import json
import time
from pathlib import Path

import pytest

from seam_sdk import Agent, EnrollProof, SeamAdminClient, enroll_pop, enroll_pop_payload
from seam_sdk._gen.seam.api.v1 import seam_pb2 as pb
from seam_sdk.crypto import (
    ENROLL_POP_V1_CONTEXT,
    validate_enroll_pop_nonce,
    verify_enroll_pop,
)

VECTOR = (
    Path(__file__).resolve().parents[2]
    / "conformance"
    / "enroll_pop_v1_payload_vector.json"
)


def _vector() -> dict:
    return json.loads(VECTOR.read_text())


def _cases() -> list[dict]:
    return _vector()["cases"]


def _b64url_decode(s: str) -> bytes:
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def test_vector_file_is_present_and_populated() -> None:
    """Parametrising over an empty list collects zero tests and reports green, so fail loudly here."""
    assert VECTOR.exists(), f"conformance vector missing: {VECTOR}"
    assert len(_cases()) >= 6, "the vector lost cases; it pins a wire contract"


def test_context_tag_matches_the_vector() -> None:
    assert ENROLL_POP_V1_CONTEXT.decode() == _vector()["domain"]


@pytest.mark.parametrize("case", _cases(), ids=lambda c: c["name"])
def test_payload_matches_the_vector_bytes(case: dict) -> None:
    got = enroll_pop_payload(
        case["subject_aid"],
        case["tenant"],
        case["namespace"],
        case["issued_at_ms"],
        case["nonce"],
    )
    assert got.hex() == case["payload_hex"]


@pytest.mark.parametrize("case", _cases(), ids=lambda c: c["name"])
def test_signature_matches_the_vector_raw_and_base64url(case: dict) -> None:
    """Ed25519 is deterministic, so the signature is exact. gRPC carries it RAW (64 bytes); the vector
    and the REST body carry it as unpadded base64url. Both representations must match."""
    agent = Agent(bytes.fromhex(case["seed_hex"]))
    assert agent.aid == case["subject_aid"]
    proof = agent.enrolment_proof(
        case["tenant"],
        case["namespace"],
        issued_at_ms=case["issued_at_ms"],
        nonce=case["nonce"],
    )
    assert proof.signature == _b64url_decode(case["signature"])  # raw — the gRPC form
    assert len(proof.signature) == 64
    assert (
        proof.signature_b64url == case["signature"]
    )  # unpadded base64url — the REST form
    assert "=" not in proof.signature_b64url
    assert proof.to_rest() == {
        "issued_at_ms": case["issued_at_ms"],
        "nonce": case["nonce"],
        "signature": case["signature"],
    }
    assert proof == enroll_pop(
        agent.seed,
        case["tenant"],
        case["namespace"],
        issued_at_ms=case["issued_at_ms"],
        nonce=case["nonce"],
    )
    assert verify_enroll_pop(
        case["subject_aid"],
        case["tenant"],
        case["namespace"],
        case["issued_at_ms"],
        case["nonce"],
        proof.signature,
    )


def test_a_proof_for_one_tenant_and_namespace_does_not_verify_for_another() -> None:
    agent = Agent(bytes(range(32)))
    proof = agent.enrolment_proof(
        "tenant-a", "ns-x", issued_at_ms=1_760_000_000_000, nonce="n0"
    )

    def verifies(tenant: str, namespace: str) -> bool:
        return verify_enroll_pop(
            agent.aid,
            tenant,
            namespace,
            proof.issued_at_ms,
            proof.nonce,
            proof.signature,
        )

    assert verifies("tenant-a", "ns-x")
    assert not verifies("tenant-b", "ns-x")
    assert not verifies("tenant-a", "ns-y")
    assert not verifies("tenant-b", "ns-y")
    # ... nor for another subject AID, time or nonce.
    other = Agent(bytes([9] * 32))
    assert not verify_enroll_pop(
        other.aid, "tenant-a", "ns-x", proof.issued_at_ms, proof.nonce, proof.signature
    )
    assert not verify_enroll_pop(
        agent.aid,
        "tenant-a",
        "ns-x",
        proof.issued_at_ms + 1,
        proof.nonce,
        proof.signature,
    )
    assert not verify_enroll_pop(
        agent.aid, "tenant-a", "ns-x", proof.issued_at_ms, "n1", proof.signature
    )


def test_enrolment_proof_defaults_to_now_and_a_fresh_22_char_nonce() -> None:
    agent = Agent(bytes(range(32)))
    before = int(time.time() * 1000)
    a = agent.enrolment_proof("acme", "fraud")
    b = agent.enrolment_proof("acme", "fraud")
    after = int(time.time() * 1000)
    assert before <= a.issued_at_ms <= after
    assert len(a.nonce) == 22 and validate_enroll_pop_nonce(a.nonce) == a.nonce
    assert a.nonce != b.nonce, "the default nonce must be random per proof"
    assert verify_enroll_pop(
        agent.aid, "acme", "fraud", a.issued_at_ms, a.nonce, a.signature
    )


@pytest.mark.parametrize("nonce", ["a", "A-z_09", "x" * 128])
def test_valid_nonces_are_accepted(nonce: str) -> None:
    assert validate_enroll_pop_nonce(nonce) == nonce


@pytest.mark.parametrize(
    "nonce",
    ["", "x" * 129, "has space", "pad=", "a+b", "a/b", "é", "a.b"],
    ids=["empty", "129", "space", "pad", "plus", "slash", "non-ascii", "dot"],
)
def test_invalid_nonces_are_refused_before_signing(nonce: str) -> None:
    with pytest.raises(ValueError, match="nonce"):
        validate_enroll_pop_nonce(nonce)
    with pytest.raises(ValueError, match="nonce"):
        Agent(bytes(range(32))).enrolment_proof("acme", "fraud", nonce=nonce)


def test_issued_at_ms_is_a_u64() -> None:
    agent = Agent(bytes(range(32)))
    with pytest.raises(ValueError, match="issued_at_ms"):
        agent.enrolment_proof("acme", "fraud", issued_at_ms=-1, nonce="n")
    with pytest.raises(ValueError, match="issued_at_ms"):
        agent.enrolment_proof("acme", "fraud", issued_at_ms=1 << 64, nonce="n")
    with pytest.raises(TypeError):
        agent.enrolment_proof("acme", "fraud", issued_at_ms=True, nonce="n")


# ── enroll_tenant wiring ───────────────────────────────────────────────────────────────────────────


def _recording_admin() -> tuple[SeamAdminClient, list]:
    seen: list = []

    class _Admin:
        def EnrollTenant(self, req, timeout):
            seen.append(req)
            return pb.TenantView(
                aid=req.subject_aid, tenant=req.tenant, namespace=req.namespace
            )

    admin = object.__new__(SeamAdminClient)
    admin._admin = _Admin()
    return admin, seen


def test_enroll_tenant_carries_pop_when_given_and_omits_it_when_not() -> None:
    agent = Agent(bytes(range(32)))
    proof = agent.enrolment_proof("acme", "fraud")
    admin, seen = _recording_admin()

    admin.enroll_tenant(agent.aid, "acme", "fraud", pop=proof)
    admin.enroll_tenant(agent.aid, "acme", "fraud")
    with_pop, without_pop = seen

    assert with_pop.HasField("pop")
    assert with_pop.pop.issued_at_ms == proof.issued_at_ms
    assert with_pop.pop.nonce == proof.nonce
    assert (
        with_pop.pop.signature == proof.signature
    )  # RAW 64 bytes on gRPC, not base64url
    assert verify_enroll_pop(
        with_pop.subject_aid,
        with_pop.tenant,
        with_pop.namespace,
        with_pop.pop.issued_at_ms,
        with_pop.pop.nonce,
        with_pop.pop.signature,
    )
    assert not without_pop.HasField("pop")


def test_enroll_tenant_accepts_a_generated_enroll_pop() -> None:
    agent = Agent(bytes(range(32)))
    proof = agent.enrolment_proof("acme", "fraud")
    admin, seen = _recording_admin()
    admin.enroll_tenant(
        agent.aid,
        "acme",
        "fraud",
        pop=pb.EnrollPop(
            issued_at_ms=proof.issued_at_ms,
            nonce=proof.nonce,
            signature=proof.signature,
        ),
    )
    assert seen[0].pop.signature == proof.signature


@pytest.mark.parametrize(
    "bad, err",
    [
        (EnrollProof(issued_at_ms=1, nonce="", signature=b"\x00" * 64), ValueError),
        (EnrollProof(issued_at_ms=1, nonce="a b", signature=b"\x00" * 64), ValueError),
        (
            EnrollProof(issued_at_ms=1, nonce="x" * 129, signature=b"\x00" * 64),
            ValueError,
        ),
        (EnrollProof(issued_at_ms=1, nonce="ok", signature=b"\x00" * 63), ValueError),
        (EnrollProof(issued_at_ms=-1, nonce="ok", signature=b"\x00" * 64), ValueError),
        (EnrollProof(issued_at_ms=1, nonce="ok", signature="A" * 86), TypeError),  # type: ignore[arg-type]
        ({"issued_at_ms": 1, "nonce": "ok", "signature": b"\x00" * 64}, TypeError),
    ],
    ids=[
        "empty-nonce",
        "bad-char",
        "long-nonce",
        "short-sig",
        "neg-time",
        "b64-sig",
        "dict",
    ],
)
def test_enroll_tenant_refuses_a_malformed_pop_before_any_rpc(bad, err) -> None:
    admin, seen = _recording_admin()
    with pytest.raises(err):
        admin.enroll_tenant("aid:x", "acme", "fraud", pop=bad)
    assert seen == [], "a malformed pop reached the wire"
