"""The cross-language conformance test for the `call_sig` v3 signed payload (#197).

Asserts against `conformance/call_sig_v3_payload_vector.json`, a byte-identical copy of the runtime's
fixture, which was generated by an implementation independent of both Rust ones. As with v2, a
self-consistent signature is not a conformant one, so these tests compare against those bytes and not
against our own output. There is no bless mode: a mismatch is a contract break.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from seam_sdk._authorize import build_authorize_request
from seam_sdk.crypto import (
    CALL_SIG_V3_CONTEXT,
    call_sig_v3,
    call_sig_v3_payload,
    tool_input_digest,
    jcs_canonicalize,
)

VECTOR = (
    Path(__file__).resolve().parents[2]
    / "conformance"
    / "call_sig_v3_payload_vector.json"
)
SEED = bytes(range(32))


def _vector() -> dict:
    return json.loads(VECTOR.read_text())


def _cases() -> list[dict]:
    return _vector()["cases"]


def _payload(case: dict) -> bytes:
    return call_sig_v3_payload(
        bytes.fromhex(case["ticket_hex"]),
        case["tool_input_digest"],
        case["tool_name"],
        case["agent_id"],
        subject=case["subject"],
        subjects=case["subjects"],
        client_request_id=case["client_request_id"],
        session_id=case["session_id"],
        features=dict(case["features"]),
    )


def test_vector_file_is_present_and_populated() -> None:
    """Parametrising over an empty list collects zero tests and reports green, so fail loudly here."""
    assert VECTOR.exists(), f"conformance vector missing: {VECTOR}"
    assert len(_cases()) >= 7, "the vector lost cases; it pins a wire contract"


def test_context_tag_matches_the_vector() -> None:
    assert CALL_SIG_V3_CONTEXT.decode() == _vector()["domain"]


@pytest.mark.parametrize("case", _cases(), ids=lambda c: c["name"])
def test_payload_matches_the_vector_bytes(case: dict) -> None:
    assert _payload(case).hex() == case["payload_hex"]


def test_the_signature_verifies_over_the_payload() -> None:
    case = next(c for c in _cases() if c["name"] == "full")
    sig = call_sig_v3(
        SEED,
        bytes.fromhex(case["ticket_hex"]),
        case["tool_input_digest"],
        tool_name=case["tool_name"],
        agent_id=case["agent_id"],
        subject=case["subject"],
        subjects=case["subjects"],
        client_request_id=case["client_request_id"],
        session_id=case["session_id"],
        features=dict(case["features"]),
    )
    Ed25519PrivateKey.from_private_bytes(SEED).public_key().verify(sig, _payload(case))


def test_authorize_requests_are_signed_v3_over_their_own_wire_fields() -> None:
    """The request builder must sign v3 over exactly what it puts on the wire, so the runtime's
    rebuild of the payload from the received request verifies."""
    req = build_authorize_request(
        ticket=b"\x01" * 16,
        agent_seed=SEED,
        tool_name="read_file",
        tool_input={"path": "/tmp/x"},
        features={"region": "eu", "amount_bucket": "high"},
        session_id="sess-9",
        subject="user-1",
        subjects=["user-3", "user-2"],
        agent_id="billing-agent",
        client_request_id="req-0001",
    )
    payload = call_sig_v3_payload(
        req.ticket,
        req.tool_input_digest,
        req.tool_name,
        req.agent_id,
        subject=req.subject,
        subjects=list(req.subjects),
        client_request_id=req.client_request_id,
        session_id=req.session_id,
        features=dict(req.features),
    )
    assert req.tool_input_digest == tool_input_digest(
        jcs_canonicalize({"path": "/tmp/x"})
    )
    Ed25519PrivateKey.from_private_bytes(SEED).public_key().verify(
        req.call_sig, payload
    )


def test_features_sort_by_utf8_bytes_not_utf16_order() -> None:
    """U+FFFF is EF BF BF in UTF-8 and U+10000 is F0 90 80 80, so bytewise U+FFFF sorts first; UTF-16
    order (D800 DC00 < FFFF) would put U+10000 first. No vector case tells the two apart, so pin it
    here — the JVM and TS twins carry the same test."""
    case = _cases()[0]
    p = call_sig_v3_payload(
        bytes.fromhex(case["ticket_hex"]),
        case["tool_input_digest"],
        case["tool_name"],
        case["agent_id"],
        features={"\U00010000": "b", "￿": "a"},
    )
    want = (
        "04000000" + "02000000" + "03000000efbfbf" + "0100000061"
        "04000000f0908080" + "0100000062"
    )
    assert p.hex().endswith(want)
