"""The declared ``grpcio`` floor must support the calling convention ``_gen`` was emitted with.

The sibling of ``test_protobuf_floor.py``, and it exists because the same defect was sitting three
lines away in the same dependency list while that one was being fixed. ``pyproject.toml`` declared
``grpcio>=1.60`` while the generated stubs use grpc's **registered-method** convention, which no
1.60 has.

What makes this one nastier than the protobuf case is that it takes TWO different versions to
satisfy, on two different sides of the contract, and the first one you find is not the answer:

* ``channel.unary_unary(..., _registered_method=True)`` — client side, grpcio **1.63**.
* ``server.add_registered_method_handlers(...)`` — server side, grpcio **1.64**, emitted with no
  ``hasattr`` guard.

Check only the client half and you conclude 1.63, ship it, and a consumer installs cleanly,
connects successfully, and then dies with ``AttributeError: '_Server' object has no attribute
'add_registered_method_handlers'`` the moment it registers a servicer. Both halves were verified
empirically against real installs, not read off a changelog:

    grpcio 1.60.0  unary_unary(_registered_method=True) -> TypeError   add_registered_...-> ABSENT
    grpcio 1.62.0  unary_unary(_registered_method=True) -> TypeError   add_registered_...-> ABSENT
    grpcio 1.63.0  unary_unary(_registered_method=True) -> OK          add_registered_...-> ABSENT
    grpcio 1.64.0  unary_unary(_registered_method=True) -> OK          add_registered_...-> present

And, as with protobuf, pinning a number is not enough. ``_gen`` is regenerated by ``make generate``
against buf's REMOTE plugins, which track latest, so the convention the stubs use can change without
anyone editing this repo's dependency list. Unlike ``seam_pb2.py``, the grpc stub carries **no
version constant to read** — so the floor is derived from the calling-convention MARKERS actually
present in the emitted code.
"""

from __future__ import annotations

import concurrent.futures as futures
import pathlib
import re

import grpc
import pytest

REPO = pathlib.Path(__file__).parents[2]
PYPROJECT = REPO / "python" / "pyproject.toml"
GEN = REPO / "python" / "seam_sdk" / "_gen"

#: marker present in the emitted stubs -> the grpcio version that first understood it.
#: Verified by installing each version and calling it, not by reading release notes.
_MARKERS: list[tuple[str, tuple[int, int], str]] = [
    (
        "_registered_method=True",
        (1, 63),
        "client stubs pass `_registered_method=True` to channel.unary_unary; older grpcio raises "
        "TypeError at stub construction, i.e. inside SeamClient.connect()",
    ),
    (
        "add_registered_method_handlers",
        (1, 64),
        "add_*Servicer_to_server calls server.add_registered_method_handlers() unguarded; older "
        "grpcio raises AttributeError for anyone registering a servicer",
    ),
]

_FLOOR_RE = re.compile(r'"grpcio>=(?P<major>\d+)\.(?P<minor>\d+)(?:\.\d+)?"')


def _stub_sources() -> list[pathlib.Path]:
    if not GEN.exists():
        pytest.skip(
            f"{GEN.relative_to(REPO)} is absent — run `make generate` first "
            "(the CI job does, before it runs these tests)"
        )
    sources = sorted(GEN.rglob("*_pb2_grpc.py"))
    assert sources, (
        f"no *_pb2_grpc.py under {GEN.relative_to(REPO)} — this guard would pass vacuously, so it "
        "fails instead: either generation is broken or the layout moved"
    )
    return sources


def _markers_present() -> list[tuple[str, tuple[int, int], str]]:
    blob = "\n".join(p.read_text(encoding="utf-8") for p in _stub_sources())
    return [entry for entry in _MARKERS if entry[0] in blob]


def _declared_floor() -> tuple[int, int]:
    match = _FLOOR_RE.search(PYPROJECT.read_text(encoding="utf-8"))
    assert match is not None, (
        "python/pyproject.toml must declare grpcio as `grpcio>=MAJOR.MINOR[.PATCH]` so this guard "
        "can compare it against what the generated stubs actually require"
    )
    return int(match["major"]), int(match["minor"])


def test_the_emitted_stubs_use_a_convention_this_guard_recognises():
    """If a regenerate emits code using NONE of the known markers, the derivation below has nothing
    to work with and would pass while checking nothing.

    That is the failure mode a derived guard has and a pinned number does not, so it is asserted
    rather than assumed: grpc changed its calling convention once already, which is why this file
    exists.
    """
    assert _markers_present(), (
        f"none of the known calling-convention markers {[m for m, _, _ in _MARKERS]} appear in the "
        "generated grpc stubs. The plugin's output convention changed; add the new marker and the "
        "grpcio version that introduced it to _MARKERS, rather than deleting this test"
    )


def test_the_declared_floor_covers_every_convention_the_stubs_use():
    """The bug, stated directly. The floor must be >= the LATEST marker present, not the first one
    found — the client-side marker alone gives 1.63, which is a version where the server side of
    these very same files raises AttributeError."""
    present = _markers_present()
    required = max(version for _, version, _ in present)
    declared = _declared_floor()
    culprit = next(entry for entry in present if entry[1] == required)
    assert declared >= required, (
        f"pyproject declares grpcio>={declared[0]}.{declared[1]} but the generated stubs need "
        f">={required[0]}.{required[1]}: {culprit[2]}. A resolver may install a grpcio that cannot "
        "run this package's own transport — and the failure lands in the CONSUMER's process, at "
        "connect() or at servicer registration, not here."
    )


def test_the_installed_grpcio_satisfies_the_declared_floor():
    installed = tuple(int(part) for part in grpc.__version__.split(".")[:2])
    declared = _declared_floor()
    assert installed >= declared, (
        f"installed grpcio {grpc.__version__} is below this package's own declared floor "
        f">={declared[0]}.{declared[1]} — the environment contradicts the metadata"
    )


def test_the_client_side_convention_actually_works_here():
    """Behavioural, not version arithmetic. This is what fails on grpcio 1.60-1.62, and it catches a
    convention change this file has no marker for — an unknown-marker regression that slips past the
    derivation above still fails here, against the grpcio that is really installed."""
    from seam_sdk._gen.seam.api.v1 import seam_pb2_grpc as rpc

    channel = grpc.insecure_channel("127.0.0.1:1")
    try:
        rpc.SeamAdmissionStub(channel)
        rpc.SeamAuthorizationStub(channel)
    finally:
        channel.close()


def test_the_server_side_convention_actually_works_here():
    """The half that a client-only check misses entirely — and the reason the floor is 1.64 rather
    than 1.63. Every test fixture in this suite registers a servicer, so a break here is loud; but
    it would be loud in a way that blames the fixture rather than the dependency floor."""
    from seam_sdk._gen.seam.api.v1 import seam_pb2_grpc as rpc

    server = grpc.server(futures.ThreadPoolExecutor(max_workers=1))
    try:
        rpc.add_SeamAdmissionServicer_to_server(rpc.SeamAdmissionServicer(), server)
        rpc.add_SeamAuthorizationServicer_to_server(
            rpc.SeamAuthorizationServicer(), server
        )
    finally:
        server.stop(None)
