"""The cross-language conformance test for the per-request credential's signed payload (#508).

Mirrors ``test_call_sig_payload.py``'s structure and the lesson behind it: a self-consistent
signature is not a conformant one. These tests assert against bytes generated by executing the
runtime's Rust ``request_sig_payload``, not against our own output.

There is deliberately no bless mode: a mismatch here is a CONTRACT BREAK, not a prompt to
regenerate the vector.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from seam_sdk.crypto import REQUEST_SIG_CONTEXT, request_sig, request_sig_payload

VECTOR = (
    Path(__file__).resolve().parents[2]
    / "conformance"
    / "request_sig_payload_vector.json"
)


def _vector() -> dict:
    return json.loads(VECTOR.read_text())


def _cases() -> list[dict]:
    return _vector()["cases"]


def test_vector_file_is_present_and_populated() -> None:
    """A missing or emptied vector must fail loudly — parametrising over an empty list silently
    collects zero tests and reports green, the same class of non-event that let call_sig's v1/v2
    skew ship (see test_call_sig_payload.py)."""
    assert VECTOR.exists(), f"conformance vector missing: {VECTOR}"
    assert len(_cases()) >= 6, "the vector lost cases; it pins a wire contract"


def test_domain_tag_matches_the_vector() -> None:
    """The tag IS the version. If the runtime bumps it and we do not, every credentialed call is
    rejected. It must also differ from `seam-authorize-call-v2`, so a captured Authorize call_sig
    is never spendable here and vice versa."""
    assert REQUEST_SIG_CONTEXT.decode() == _vector()["domain"]
    from seam_sdk.crypto import CALL_SIG_CONTEXT

    assert REQUEST_SIG_CONTEXT != CALL_SIG_CONTEXT


@pytest.mark.parametrize("case", _cases(), ids=lambda c: c["name"])
def test_payload_matches_the_runtime_bytes(case: dict) -> None:
    got = request_sig_payload(
        bytes.fromhex(case["ticket_hex"]),
        case["rpc_full_name"],
        case["resource_id"],
        case["body_digest"],
    )
    assert got.hex() == case["payload_hex"], (
        f"request_sig payload diverged from the runtime for case {case['name']!r}.\n"
        f"  expected {case['payload_hex']}\n  actual   {got.hex()}\n"
        "This is a wire CONTRACT BREAK. Do not regenerate the vector to make this pass."
    )


@pytest.mark.parametrize(
    "case", [c for c in _cases() if "body_input_hex" in c], ids=lambda c: c["name"]
)
def test_body_digest_matches_the_pinned_computation(case: dict) -> None:
    """The two bodied-verb cases pin the DIGEST COMPUTATION, not just the framing around it — an
    implementation that reproduces every payload byte-for-byte can still get the digest wrong if it
    hashes a re-serialization rather than the exact bytes given here."""
    import hashlib

    body = bytes.fromhex(case["body_input_hex"])
    assert case["body_digest"] == "sha256:" + hashlib.sha256(body).hexdigest()


def test_same_ticket_and_resource_different_verb_produce_different_payloads() -> None:
    """THE re-pointing guard: an implementation that omits rpc_full_name from the payload produces
    the same bytes for a structural read and the decrypted proof it sits beside."""
    a = request_sig_payload(
        b"\x01", "/seam.api.v1.SeamCoordination/GetDecision", "dec:1", ""
    )
    b = request_sig_payload(
        b"\x01", "/seam.api.v1.SeamCoordination/GetCommitmentProof", "dec:1", ""
    )
    assert a != b


def test_length_prefixes_disambiguate_adjacent_fields() -> None:
    """Without length prefixes, a boundary shift between rpc_full_name and resource_id can make two
    different (verb, resource) pairs concatenate identically — reopening the re-pointing gap the
    framing exists to close."""
    a = request_sig_payload(b"", "/seam.api.v1.SeamCoordination/Replay", "x", "")
    b = request_sig_payload(b"", "/seam.api.v1.SeamCoordination/Replayx", "", "")
    assert a != b


def test_lengths_are_byte_counts_not_character_counts() -> None:
    """Lengths are BYTES. A UTF-16 or code-point length (JavaScript's .length, Python's len on str)
    produces a shorter prefix and an unverifiable signature."""
    ascii_p = request_sig_payload(b"", "/x/Y", "s-abc", "")
    utf8_p = request_sig_payload(b"", "/x/Y", "s-é中🔐", "")
    assert len(utf8_p) > len(ascii_p)


def test_every_field_is_bound() -> None:
    """Changing any one input must change the payload — a field accepted but not actually mixed in
    verifies locally and is rejected by the runtime, which is the worst version of this bug."""
    base = dict(
        ticket=b"t",
        rpc_full_name="/seam.api.v1.SeamCoordination/GetDecision",
        resource_id="dec:1",
        body_digest="sha256:aa",
    )
    baseline = request_sig_payload(**base)
    for field, altered in [
        ("ticket", b"T"),
        ("rpc_full_name", "/seam.api.v1.SeamCoordination/ReplayDecision"),
        ("resource_id", "dec:2"),
        ("body_digest", "sha256:bb"),
    ]:
        assert request_sig_payload(**{**base, field: altered}) != baseline, (
            f"{field} is not bound into the payload"
        )


def test_signature_verifies_over_the_payload() -> None:
    seed = bytes(range(32))
    sk = Ed25519PrivateKey.from_private_bytes(seed)
    sig = request_sig(
        seed, b"ticket", "/seam.api.v1.SeamCoordination/GetDecision", "dec:1", ""
    )
    sk.public_key().verify(
        sig,
        request_sig_payload(
            b"ticket", "/seam.api.v1.SeamCoordination/GetDecision", "dec:1", ""
        ),
    )


def test_request_sig_does_not_verify_against_a_call_sig_payload() -> None:
    """The two credentials use different domain tags, so a captured one must never verify as the
    other — even when every other input happens to collide."""
    from seam_sdk.crypto import call_sig_payload

    seed = bytes(range(32))
    sk = Ed25519PrivateKey.from_private_bytes(seed)
    sig = sk.sign(call_sig_payload(b"t", "d", "n", "a"))
    with pytest.raises(Exception):
        sk.public_key().verify(sig, request_sig_payload(b"t", "d", "n", "a"))
